# Created by: Martin Wilke <miwi@FreeBSD.org>

PORTNAME=	psycopg
PORTVERSION=	3.0
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	High performance Python adapter for PostgreSQL

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		pgsql python:3.6+
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
